language: python
python:
- '2.7'
script: echo "success"
deploy:
  provider: heroku
  app: serene-tor-17655
  api_key:
    secure: cUM2aFg3995U7QNH88kxBr3JhdgCxCJrTl2slWUrJsslwDvTP2xN8YhXPvLTp6YbR3LouTj0IY3nZkDg7BAm12SqWeVdbCbq1WtrR0kvAaVU9NqRXTJfkabR2gFqCuODnrxMjEk1qR/KkK6/6XlPCVehAK/Xb7Ng7h41kiOFjog=
