language: python
python:
- 2.7.9
install:
- pip install -r requirements.txt
script: echo foo
deploy:
  provider: heroku
  api_key:
  secure: "W642O817fydXyv1FkjGfNwZztraMxF/lOZrLhQiLb57AEiTo//FbwBxvIZH/nOH1bPEBj2r+F05mdsdNkT7IMy2tMKeZDJnKYx2AN9BKYo294vF0+U/p3AyOIgejdpsNPKOYFZxkVd/VdqVQSp2a3H82VIL5gb+MM1i0//GPpfo="




