language: python
python:
- '2.7'
script: echo "success"
deploy:
  provider: heroku
  api_key:
    secure: e9m2O1ANuA7MB3iVa5iYNlXZy39YOEmkBlyJmaV/hSfAREFexFcBOvidhwdDbp/YkQpjCIxBMz0q0xyKweIFz9WvNKd50KDqSKa+vT1Lz1qpiQybbf293cdfYFPmim9HTReamH7TdQ4Cyb/VfJpGq2tWxAuptnyVR9kGo8OUF7w=
  app: serene-tor-17655
  on:
    repo: heroku/python-getting-started
notifications:
  slack:
    rooms:
      - pekteamgroup:OoJVNgVCp0ZDAHWnsOoa4Wjj#travis-updates