language: python
python:
- 2.7.9
install:
- pip install -r requirements.txt
script: echo foo
deploy:
  provider: heroku
  api_key:
    secure: "VC+IN8ofqEWkoTnw7e9gHFwH3XSgD7IrDWMtbU0T1ErvKYUAUcjjORdZR9KzPsKizko7lKZ43o4Di1eIGUya6SA9QGwRD3kYXvUzzDyJgawMs29WdmQATYgIOHTaioECQ1t/B0hBEz4VWU5zn0YXzepgl+6RSv+e7oW2SYnH85E="
